dependencies:
  - name: postgresql
    version: latest
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
  - name: mysql
    version: 0.6.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mysql.enabled
